server:
  port: 8090
  servlet:
    context-path: /api
spring:
  datasource:
    password: Alejandro95
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    show-sql: true
  jackson:
    time-zone: America/Mexico_City
    locale: es_MX
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
        
        
      